language: c
compiler:
    - gcc
    - clang
addons:
    apt:
        packages:
            - xmlto
script: "./configure && make"
branches:
    only:
        - master
notifications:
    recipients:
        - max.c.lv@gmail.com
    email:
        on_success: change
        on_failure: always
